// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {PlasmicAuth} from "./plasmic/website_starter/PlasmicAuth";
import {useState} from "react";
import {Cookies} from "react-cookie"
import {createClient} from '@/utils/supabase/client'
import {useRouter} from "next/router";
import { mutate } from "swr";
import { PLASMIC_AUTH_DATA_KEY } from "../utils/cache-keys";

function Auth_(props, ref) {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const router = useRouter();
    const supabase = createClient();
    const cookies = new Cookies();
    return (<PlasmicAuth root={{ref}} {...props}
                         emailInput={{
                             value: email,
                             onChange: (e) => setEmail(e.target.value)
                         }
                         }
                         passwordInput={{
                             value: password,
                             onChange: (e) => setPassword(e.target.value)
                         }}
                         submitButton={{
                             onClick: async () => {
                                 let loginfunc = null

                                 loginfunc = await supabase.auth.signInWithPassword({
                                   email: email,
                                   password: password
                                 })

                                 const {data} = loginfunc;
                                 console.info(data)
                                 const {error} = loginfunc
                                 if (error) {
                                     return console.log(error)
                                 }
                                 await mutate(PLASMIC_AUTH_DATA_KEY);
                                 router.push("/")

                             }
                         }}
    />);
}

const Auth = React.forwardRef(Auth_);

export default Auth;
