// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {PlasmicLogout2} from "./plasmic/website_starter/PlasmicLogout2";
import {createClient} from "@/utils/supabase/client";
import {useRouter} from "next/router";
import {mutate} from "swr";
import {PLASMIC_AUTH_DATA_KEY} from "@/utils/cache-keys";

function Logout2_(props, ref) {
    const supabase = createClient();
    const router = useRouter();
    return <PlasmicLogout2 root={{ref}} {...props}
                           lgButton={{
                               onClick: async () => {
                                   // console.log('Clickkk')
                                   let loginfunc = await supabase.auth.signOut()
                                   await mutate(PLASMIC_AUTH_DATA_KEY);
                                   console.log(loginfunc)
                                   router.replace("/login")
                               }
                           }}


    />;
}

const Logout2 = React.forwardRef(Logout2_);

export default Logout2;
