// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicLogoutbtn } from "./plasmic/website_starter/PlasmicLogoutbtn";

function Logoutbtn(props) {

  return <PlasmicLogoutbtn {...props} />;
}

export default Logoutbtn;
